
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-19T13:52:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "54046c1e5624af95baa414833f96e2b70d02ca0f",
 "version": "1.9.7-dev.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
