from pkg_resources import parse_requirements
import setuptools

setuptools.setup(
    name="PyEnzymeKinetics",
    version="1.1.4",
    url="https://github.com/haeussma/PyEnzymeKinetics",
    author="Haeussler, Max",
    author_email="max.haeussler@gmail.com",
    packages=setuptools.find_packages(),
    install_requires=[
        "asteval==0.9.27",
        "cycler==0.11.0",
        "deepdiff==5.8.1",
        "deprecation==2.1.0",
        "et-xmlfile==1.1.0",
        "fonttools==4.34.4",
        "future==0.18.2",
        "kiwisolver==1.4.3",
        "lmfit==1.0.3",
        "matplotlib==3.5.2",
        "numexpr==2.8.3",
        "numpy==1.23.1",
        "openpyxl==3.0.10",
        "ordered-set==4.1.0",
        "packaging==21.3",
        "pandas==1.4.3",
        "Pillow==9.2.0",
        "plotly==5.9.0",
        "pydantic==1.8.2",
        "PyEnzyme==1.1.4",
        "pyparsing==3.0.9",
        "python-dateutil==2.8.2",
        "python-libcombine==0.2.18",
        "python-libsbml==5.19.5",
        "python-multipart==0.0.5",
        "pytz==2022.1",
        "PyYAML==5.4.1",
        "scipy==1.8.1",
        "seaborn==0.11.2",
        "six==1.16.0",
        "tenacity==8.0.1",
        "texttable==1.6.4",
        "typing_extensions==4.3.0",
        "uncertainties==3.1.7",
        "XlsxWriter==3.0.3"
    ]
)
