#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['python_x509_pkcs11']

package_data = \
{'': ['*'],
 'python_x509_pkcs11': ['.mypy_cache/*',
                        '.mypy_cache/3.7/*',
                        '.mypy_cache/3.7/_typeshed/*',
                        '.mypy_cache/3.7/collections/*',
                        '.mypy_cache/3.7/importlib/*',
                        '.mypy_cache/3.7/os/*',
                        '.mypy_cache/3.7/python_x509_pkcs11/*']}

package_dir = \
{'': 'src'}

install_requires = \
['asn1crypto>=1.4.0', 'python-pkcs11>=0.7.0']

setup(name='python_x509_pkcs11',
      version='0.2.23',
      description='python_x509_pkcs11 package init file',
      author='Victor Näslund',
      author_email='victor@sunet.se',
      url='https://github.com/SUNET/python_x509_pkcs11',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      python_requires='>=3.7',
     )
