
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-15T11:47:40-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f28888de67af2505665a6f3abd7f0ad042af4425",
 "version": "1.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
