
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T11:26:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba629a5dc1340060a4e965ff45dd166ddaba58d1",
 "version": "2695"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
