
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-19T16:35:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4656c0e87e42eddac4585fb24cf6051b445573aa",
 "version": "2.0b9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
