
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T03:44:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5aa75432b4c648c49def02f1b4bcfaaa67bb54c3",
 "version": "1.17.0.post.dev34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
