# AUTOGENERATED! DO NOT EDIT! File to edit: 04_emotional_plot.ipynb (unless otherwise specified).

__all__ = ['get_vec', 'label2vector', 'check_label2int']

# Cell
from .model_api import *

# Cell
import numpy as np

# Cell
# helpful when changing the value of each emotional vector
# e.g., label2vector['anger'] = get_vec(1,2)
# , which will change the vector value of 'anger' to np.array([1,2])
# pay attention to the shape when plotting
# *args allows us to input as many dimension as we want, see examples below
def get_vec(*args):
    return np.array(args).reshape(-1,1)

# Cell
label2vector = {'sadness': np.array([[-0.5],
        [-0.5]]),
 'joy': np.array([[0.5],
        [0.5]]),
 'love': np.array([[0.8],
        [0. ]]),
 'anger': np.array([[-0.8],
        [ 0.8]]),
 'fear': np.array([[-0.8],
        [ 0. ]]),
 'surprise': np.array([[0.8],
        [0.8]])}

# Cell
"""if you want to see the original map, just use this"""
def check_label2int(print_it=True):
    if print_it:
        for key in label2int:
            print(key,":",label2int[key])
    return label2int