
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-15T20:45:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "045e9ff8562a7191e3c5e9c8e39ea972df06527f",
 "version": "0.45.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
