
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-20T11:07:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d210c08eb98be62350d77d76f70e3e14d19656a",
 "version": "1.0.5.post.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
