
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-13T12:14:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "50e2d35f40e0d7b0979966cded8351511d9e1d6a",
 "version": "3.11.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
