
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T03:22:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a500949daf16dec09725a2752f87d774c27c845",
 "version": "1.17.0.post.dev31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
