
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T12:20:25-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "cac73baef06f27aac80291ff75e87f6f049b04fc",
 "version": "2.7.7.dev20220716"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
