
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T16:22:15+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "932d1280344c744ad3707005ee4c7f6a5bc47c8c",
 "version": "0.28.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
