# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/logged_model_metric.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$api/entity/logged_model_metric.proto\x12\x03\x61pi\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x01\n\x11LoggedModelMetric\x12\x12\n\nunique_tag\x18\x01 \x01(\t\x12\x37\n\x06points\x18\x02 \x03(\x0b\x32\'.api.LoggedModelMetric.ModelMetricPoint\x12\x30\n\x0c\x63reated_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0cupdated_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\x30\n\x10ModelMetricPoint\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x01\x42\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_LOGGEDMODELMETRIC = DESCRIPTOR.message_types_by_name['LoggedModelMetric']
_LOGGEDMODELMETRIC_MODELMETRICPOINT = _LOGGEDMODELMETRIC.nested_types_by_name['ModelMetricPoint']
LoggedModelMetric = _reflection.GeneratedProtocolMessageType('LoggedModelMetric', (_message.Message,), {

  'ModelMetricPoint' : _reflection.GeneratedProtocolMessageType('ModelMetricPoint', (_message.Message,), {
    'DESCRIPTOR' : _LOGGEDMODELMETRIC_MODELMETRICPOINT,
    '__module__' : 'api.entity.logged_model_metric_pb2'
    # @@protoc_insertion_point(class_scope:api.LoggedModelMetric.ModelMetricPoint)
    })
  ,
  'DESCRIPTOR' : _LOGGEDMODELMETRIC,
  '__module__' : 'api.entity.logged_model_metric_pb2'
  # @@protoc_insertion_point(class_scope:api.LoggedModelMetric)
  })
_sym_db.RegisterMessage(LoggedModelMetric)
_sym_db.RegisterMessage(LoggedModelMetric.ModelMetricPoint)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _LOGGEDMODELMETRIC._serialized_start=79
  _LOGGEDMODELMETRIC._serialized_end=325
  _LOGGEDMODELMETRIC_MODELMETRICPOINT._serialized_start=277
  _LOGGEDMODELMETRIC_MODELMETRICPOINT._serialized_end=325
# @@protoc_insertion_point(module_scope)
