
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-15T13:22:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1df2fc55456349e4f40ebe2a7784d6df47d7f6d0",
 "version": "2698"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
