# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: octoml/octomizer/v1/engine.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='octoml/octomizer/v1/engine.proto',
  package='octoml.octomizer.v1',
  syntax='proto3',
  serialized_options=b'Z0octoml.ai/api_rest_proxy/gen/octoml/octomizer/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n octoml/octomizer/v1/engine.proto\x12\x13octoml.octomizer.v1\"\x8b\x03\n\nEngineSpec\x12=\n\x0ftvm_engine_spec\x18\x01 \x01(\x0b\x32\".octoml.octomizer.v1.TVMEngineSpecH\x00\x12M\n\x17onnxruntime_engine_spec\x18\x02 \x01(\x0b\x32*.octoml.octomizer.v1.ONNXRuntimeEngineSpecH\x00\x12\x43\n\x12tflite_engine_spec\x18\x03 \x01(\x0b\x32%.octoml.octomizer.v1.TFLiteEngineSpecH\x00\x12L\n\x17tensor_flow_engine_spec\x18\x05 \x01(\x0b\x32).octoml.octomizer.v1.TensorFlowEngineSpecH\x00\x12M\n\x17torchscript_engine_spec\x18\x06 \x01(\x0b\x32*.octoml.octomizer.v1.TorchscriptEngineSpecH\x00\x42\r\n\x0b\x65ngine_spec\"m\n\rTVMEngineSpec\x12\x15\n\rrelay_opt_lvl\x18\x01 \x01(\r\x12\x17\n\x0f\x65nable_profiler\x18\x02 \x01(\x08\x12\x17\n\x0ftvm_num_threads\x18\x03 \x01(\r\x12\x13\n\x0btvm_version\x18\x04 \x01(\t\"5\n\x15ONNXRuntimeEngineSpec\x12\x1c\n\x14intra_op_num_threads\x18\x01 \x01(\r\"\x12\n\x10TFLiteEngineSpec\"\x16\n\x14TensorFlowEngineSpec\"\x17\n\x15TorchscriptEngineSpecB2Z0octoml.ai/api_rest_proxy/gen/octoml/octomizer/v1b\x06proto3'
)




_ENGINESPEC = _descriptor.Descriptor(
  name='EngineSpec',
  full_name='octoml.octomizer.v1.EngineSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tvm_engine_spec', full_name='octoml.octomizer.v1.EngineSpec.tvm_engine_spec', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='onnxruntime_engine_spec', full_name='octoml.octomizer.v1.EngineSpec.onnxruntime_engine_spec', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tflite_engine_spec', full_name='octoml.octomizer.v1.EngineSpec.tflite_engine_spec', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tensor_flow_engine_spec', full_name='octoml.octomizer.v1.EngineSpec.tensor_flow_engine_spec', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='torchscript_engine_spec', full_name='octoml.octomizer.v1.EngineSpec.torchscript_engine_spec', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='engine_spec', full_name='octoml.octomizer.v1.EngineSpec.engine_spec',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=58,
  serialized_end=453,
)


_TVMENGINESPEC = _descriptor.Descriptor(
  name='TVMEngineSpec',
  full_name='octoml.octomizer.v1.TVMEngineSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='relay_opt_lvl', full_name='octoml.octomizer.v1.TVMEngineSpec.relay_opt_lvl', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_profiler', full_name='octoml.octomizer.v1.TVMEngineSpec.enable_profiler', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tvm_num_threads', full_name='octoml.octomizer.v1.TVMEngineSpec.tvm_num_threads', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tvm_version', full_name='octoml.octomizer.v1.TVMEngineSpec.tvm_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=564,
)


_ONNXRUNTIMEENGINESPEC = _descriptor.Descriptor(
  name='ONNXRuntimeEngineSpec',
  full_name='octoml.octomizer.v1.ONNXRuntimeEngineSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='intra_op_num_threads', full_name='octoml.octomizer.v1.ONNXRuntimeEngineSpec.intra_op_num_threads', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=619,
)


_TFLITEENGINESPEC = _descriptor.Descriptor(
  name='TFLiteEngineSpec',
  full_name='octoml.octomizer.v1.TFLiteEngineSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=639,
)


_TENSORFLOWENGINESPEC = _descriptor.Descriptor(
  name='TensorFlowEngineSpec',
  full_name='octoml.octomizer.v1.TensorFlowEngineSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=663,
)


_TORCHSCRIPTENGINESPEC = _descriptor.Descriptor(
  name='TorchscriptEngineSpec',
  full_name='octoml.octomizer.v1.TorchscriptEngineSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=665,
  serialized_end=688,
)

_ENGINESPEC.fields_by_name['tvm_engine_spec'].message_type = _TVMENGINESPEC
_ENGINESPEC.fields_by_name['onnxruntime_engine_spec'].message_type = _ONNXRUNTIMEENGINESPEC
_ENGINESPEC.fields_by_name['tflite_engine_spec'].message_type = _TFLITEENGINESPEC
_ENGINESPEC.fields_by_name['tensor_flow_engine_spec'].message_type = _TENSORFLOWENGINESPEC
_ENGINESPEC.fields_by_name['torchscript_engine_spec'].message_type = _TORCHSCRIPTENGINESPEC
_ENGINESPEC.oneofs_by_name['engine_spec'].fields.append(
  _ENGINESPEC.fields_by_name['tvm_engine_spec'])
_ENGINESPEC.fields_by_name['tvm_engine_spec'].containing_oneof = _ENGINESPEC.oneofs_by_name['engine_spec']
_ENGINESPEC.oneofs_by_name['engine_spec'].fields.append(
  _ENGINESPEC.fields_by_name['onnxruntime_engine_spec'])
_ENGINESPEC.fields_by_name['onnxruntime_engine_spec'].containing_oneof = _ENGINESPEC.oneofs_by_name['engine_spec']
_ENGINESPEC.oneofs_by_name['engine_spec'].fields.append(
  _ENGINESPEC.fields_by_name['tflite_engine_spec'])
_ENGINESPEC.fields_by_name['tflite_engine_spec'].containing_oneof = _ENGINESPEC.oneofs_by_name['engine_spec']
_ENGINESPEC.oneofs_by_name['engine_spec'].fields.append(
  _ENGINESPEC.fields_by_name['tensor_flow_engine_spec'])
_ENGINESPEC.fields_by_name['tensor_flow_engine_spec'].containing_oneof = _ENGINESPEC.oneofs_by_name['engine_spec']
_ENGINESPEC.oneofs_by_name['engine_spec'].fields.append(
  _ENGINESPEC.fields_by_name['torchscript_engine_spec'])
_ENGINESPEC.fields_by_name['torchscript_engine_spec'].containing_oneof = _ENGINESPEC.oneofs_by_name['engine_spec']
DESCRIPTOR.message_types_by_name['EngineSpec'] = _ENGINESPEC
DESCRIPTOR.message_types_by_name['TVMEngineSpec'] = _TVMENGINESPEC
DESCRIPTOR.message_types_by_name['ONNXRuntimeEngineSpec'] = _ONNXRUNTIMEENGINESPEC
DESCRIPTOR.message_types_by_name['TFLiteEngineSpec'] = _TFLITEENGINESPEC
DESCRIPTOR.message_types_by_name['TensorFlowEngineSpec'] = _TENSORFLOWENGINESPEC
DESCRIPTOR.message_types_by_name['TorchscriptEngineSpec'] = _TORCHSCRIPTENGINESPEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EngineSpec = _reflection.GeneratedProtocolMessageType('EngineSpec', (_message.Message,), {
  'DESCRIPTOR' : _ENGINESPEC,
  '__module__' : 'octoml.octomizer.v1.engine_pb2'
  # @@protoc_insertion_point(class_scope:octoml.octomizer.v1.EngineSpec)
  })
_sym_db.RegisterMessage(EngineSpec)

TVMEngineSpec = _reflection.GeneratedProtocolMessageType('TVMEngineSpec', (_message.Message,), {
  'DESCRIPTOR' : _TVMENGINESPEC,
  '__module__' : 'octoml.octomizer.v1.engine_pb2'
  # @@protoc_insertion_point(class_scope:octoml.octomizer.v1.TVMEngineSpec)
  })
_sym_db.RegisterMessage(TVMEngineSpec)

ONNXRuntimeEngineSpec = _reflection.GeneratedProtocolMessageType('ONNXRuntimeEngineSpec', (_message.Message,), {
  'DESCRIPTOR' : _ONNXRUNTIMEENGINESPEC,
  '__module__' : 'octoml.octomizer.v1.engine_pb2'
  # @@protoc_insertion_point(class_scope:octoml.octomizer.v1.ONNXRuntimeEngineSpec)
  })
_sym_db.RegisterMessage(ONNXRuntimeEngineSpec)

TFLiteEngineSpec = _reflection.GeneratedProtocolMessageType('TFLiteEngineSpec', (_message.Message,), {
  'DESCRIPTOR' : _TFLITEENGINESPEC,
  '__module__' : 'octoml.octomizer.v1.engine_pb2'
  # @@protoc_insertion_point(class_scope:octoml.octomizer.v1.TFLiteEngineSpec)
  })
_sym_db.RegisterMessage(TFLiteEngineSpec)

TensorFlowEngineSpec = _reflection.GeneratedProtocolMessageType('TensorFlowEngineSpec', (_message.Message,), {
  'DESCRIPTOR' : _TENSORFLOWENGINESPEC,
  '__module__' : 'octoml.octomizer.v1.engine_pb2'
  # @@protoc_insertion_point(class_scope:octoml.octomizer.v1.TensorFlowEngineSpec)
  })
_sym_db.RegisterMessage(TensorFlowEngineSpec)

TorchscriptEngineSpec = _reflection.GeneratedProtocolMessageType('TorchscriptEngineSpec', (_message.Message,), {
  'DESCRIPTOR' : _TORCHSCRIPTENGINESPEC,
  '__module__' : 'octoml.octomizer.v1.engine_pb2'
  # @@protoc_insertion_point(class_scope:octoml.octomizer.v1.TorchscriptEngineSpec)
  })
_sym_db.RegisterMessage(TorchscriptEngineSpec)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
