
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T14:03:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a09dee20088e4f79d716407691dddf3d08062294",
 "version": "3.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
