
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T14:08:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "58d40a78077f309ab25e4c5c640fb7551a4f11fd",
 "version": "0.10.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
