
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T14:09:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "232f51995bc43f177475f4d1bb9870d7f4e10f92",
 "version": "0.10.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
