
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T14:44:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8cf1fc3ee31379f4e1fadfbcf5ecc750a74e93c8",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
