
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-19T12:00:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a04592ba09facf16b1f201d3cbaf2d0cc08bb1d",
 "version": "2708"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
