info = {"message": "ci: Sync .github directory from develop (#2655)", "commit": "8c657fce5928886f9da025ef271c96ececa6bbf4", "date": "2022-07-13 16:05:08 +0400", "branch": "HEAD", "version": "8c657fc+dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
