
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T15:33:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cee89bb94581e47b31b97b63b2b7ee2a26f5a2f0",
 "version": "2.0.0a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
