
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-17T02:51:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "63964a5f3dbc4e2cb7a66f2da9a385c98e87e846",
 "version": "0.10.dev2229"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
