
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-19T16:26:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "21128d9109fd2dfb7713d19d84b75464ada74932",
 "version": "2712"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
