
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-13T15:16:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ba16aab11885ea7254f644fcd6f53e3ab14dcf3",
 "version": "6.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
