
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-17T11:57:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b60d418d0846fc94797734c3a19b7f1159d16f34",
 "version": "2.0.0a7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
