
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-16T08:53:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e636ee9f02766ad3a3baf5a8f6326960c83df7dc",
 "version": "4.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
