
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-13T03:37:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5bd3afca8a1f3afc4b360ed0158b9ca084fdcfc5",
 "version": "0.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
