
# This file was generated by 'versioneer.py' (0.20.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-16T13:03:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "22b26884e04e6940cfa389afd91fd673f510c438",
 "version": "0.17.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
