
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T17:37:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "37e087331430cde7cbeef25bc616d607276ad6ec",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
