
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-15T19:45:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "85c14958bcaf10b86a8cac7e6a857e36ec2221a8",
 "version": "1.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
