
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-13T10:45:15-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d81fbd48adf560632088e49f4304922b6aa881b",
 "version": "1.9.6-dev.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
