
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-19T14:20:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5dadab50a176a90357b84e9e54ea928d8abdd23",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
