
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T22:27:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e879fe0eca19a4511a825537d039b45de0371f0e",
 "version": "0.2.14.post0.dev26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
