"""
    Cavoke

    API for cavoke interaction between main server and clients  # noqa: E501

    The version of the OpenAPI document: 0.2.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cavoke_openapi_client
from cavoke_openapi_client.model.user_statistics import UserStatistics


class TestUserStatistics(unittest.TestCase):
    """UserStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserStatistics(self):
        """Test UserStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
