
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T15:33:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "be222f0caac7f3346b2f5882c35cd03f778adecc",
 "version": "2.7.7.dev20220714"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
