"""
    Cavoke

    API for cavoke interaction between main server and clients  # noqa: E501

    The version of the OpenAPI document: 0.2.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cavoke_openapi_client
from cavoke_openapi_client.model.game_move import GameMove


class TestGameMove(unittest.TestCase):
    """GameMove unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGameMove(self):
        """Test GameMove"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GameMove()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
