
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-13T07:15:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "724e7849e3c4aa0f972cdf819ad34fe14f15af17",
 "version": "0.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
