# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {
    "DataLoader": "data_loader.ipynb",
    "create_weighted_random_sampler": "data_loader.ipynb",
    "create_sample_weights_from_multilabels": "data_loader.ipynb",
    "lookup": "data_loader.ipynb",
}

modules = ["data_loader.py"]

doc_url = "https://Kevin.github.io/core/"

git_url = "https://github.com/Kevin/core/tree/master/"


def custom_doc_links(name):
    return None
