
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-20T12:03:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2f14acc399f9f0a22457b20a2df3609bc8ec522",
 "version": "1.0.5.post.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
