# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/organization_view.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.api import ids_pb2 as api_dot_ids__pb2
from layerapi.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"api/entity/organization_view.proto\x12\x03\x61pi\x1a\rapi/ids.proto\x1a\x17validate/validate.proto\"}\n\x10OrganizationView\x12,\n\x0forganization_id\x18\x01 \x01(\x0b\x32\x13.api.OrganizationId\x12\x19\n\x11organization_name\x18\x02 \x01(\t\x12 \n\x0c\x64isplay_name\x18\x03 \x01(\tB\n\xfa\x42\x07r\x05\x10\x01\x18\x80\x02\x42\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_ORGANIZATIONVIEW = DESCRIPTOR.message_types_by_name['OrganizationView']
OrganizationView = _reflection.GeneratedProtocolMessageType('OrganizationView', (_message.Message,), {
  'DESCRIPTOR' : _ORGANIZATIONVIEW,
  '__module__' : 'api.entity.organization_view_pb2'
  # @@protoc_insertion_point(class_scope:api.OrganizationView)
  })
_sym_db.RegisterMessage(OrganizationView)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _ORGANIZATIONVIEW.fields_by_name['display_name']._options = None
  _ORGANIZATIONVIEW.fields_by_name['display_name']._serialized_options = b'\372B\007r\005\020\001\030\200\002'
  _ORGANIZATIONVIEW._serialized_start=83
  _ORGANIZATIONVIEW._serialized_end=208
# @@protoc_insertion_point(module_scope)
