
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T13:54:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7fc234777ca2302169d8400eb98816f6d1aef8a",
 "version": "2706"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
