
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-15T11:05:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d5cfb69128d2703e7b272b895f9ead981f8f35d",
 "version": "0.10.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
