
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-17T09:54:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "78e810a60c12b7a8bc950daa52fc2a1a3f7137b7",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
