
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T11:39:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4c8b06a0ebd6479d5442f95782af62268b85ec7",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
