
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-13T15:48:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6cc6e4d968921f7b0db28314b3c8409919038723",
 "version": "1.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
