
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-19T19:48:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f8619196b80317c4b14cf3c39581e5643d38431",
 "version": "1.0.5.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
