
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T20:16:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "809800c1120f0902bec63cf0d5960b37fa0cafad",
 "version": "1.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
