
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T21:45:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "75d0987ebce2d2554406503388ba66861e3d2aaf",
 "version": "0.2.14.post0.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
