
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T10:35:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a25b6a525d82f23665d67a99c164df6c896d98f",
 "version": "0.10.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
