# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"list_to_queue": "00_Evaluation_tools.ipynb",
         "goal_buffer_handler": "00_Evaluation_tools.ipynb",
         "get_value": "00_Evaluation_tools.ipynb",
         "save_to_csv": "00_Evaluation_tools.ipynb",
         "get_distance": "00_Evaluation_tools.ipynb",
         "PolicyNetwork": "01_model.ipynb",
         "uniform_initializer": "01_model.ipynb",
         "CriticNetwork": "01_model.ipynb"}

modules = ["Evaluation_tools.py",
           "model.py"]

doc_url = "https://yelloooowww.github.io/curl_navi/"

git_url = "https://github.com/yelloooowww/curl_navi/tree/master/"

def custom_doc_links(name): return None
