
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-17T02:50:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "44e3ceed1e756cbe832908ad2696e35d730b9384",
 "version": "0.4.dev2229"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
