
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-19T11:51:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "499d9c42045b7d6f0fa9b074be8a03a1a2d72624",
 "version": "0.7.1.post.dev694"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
