#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['eeghdf']

package_data = \
{'': ['*']}

install_requires = \
['numpy', 'h5py', 'pandas', 'future']

extras_require = \
{'mne': ['mne>=1.0'], 'test': ['pytest']}

setup(name='eeghdf',
      version='0.2.3',
      description='eeghdf is a module for reading a writing EEG data into the hdf5 format',
      author=None,
      author_email='Chris Lee-Messer <chris@lee-messer.net>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
     )
