#!/usr/bin/python3

#region Modules

import argparse
import colorama
from colorama import Fore
import os
import shutil
import subprocess
import time

#endregion

#region Arguments

argumentParser = argparse.ArgumentParser(description="Various arguments for the Wicky project generator.")
argumentParser.add_argument('-n', 
                            '--name', 
                            dest = 'projectName', 
                            default = "Untitled Project",
                            help = "Defines the name of the project generated by Wicky.")
arguments = argumentParser.parse_args()

#endregion

#region Variables

dividerFile = open('Text/Divider.txt', 'r')
divider = dividerFile.read()
titleFile = open('Text/Title.txt', 'r')
title = titleFile.read()
versionFile = open('Text/Version.txt', 'r')
version = versionFile.read()

templatePath = r'../Templates/Default/'
templateDestination = f'{os.getcwd()}/Destination'

nameTarget = "_REPLACE_ME_"
nameReplacement = "Untitled Project"

#endregion

# Functions

def Prompt(projectName):
    if projectName == "Untitled Project":
        projectName = input("Project name: ")
    
    templateDestination = f'{os.getcwd()}/{projectName}'
    print(f"Copying files to destination:\n{templateDestination}")

    try:
        shutil.copytree(templatePath, templateDestination)
    except FileExistsError:
        print(f"{Fore.RED}Error: {Fore.WHITE}folder '{projectName}' already exists!")

    nameReplacement = projectName

    with open(f'{templateDestination}/Source/main_SDL2.cpp', 'r') as file:
        main_SDL2_DATA = file.read()
        main_SDL2_DATA = main_SDL2_DATA.replace(nameTarget, nameReplacement)

    with open(f'{templateDestination}/Source/main_SDL2.cpp', 'w') as file:
        file.write(main_SDL2_DATA)

#endregion

# Main execution
if __name__ == '__main__':
    print(f"{Fore.RED}{title}{Fore.WHITE}")
    print(f"{Fore.WHITE}{divider}{Fore.WHITE}")
    print(f"Wicky version: {Fore.YELLOW}{version}{Fore.WHITE}")
    
    # Dramatic effect~
    time.sleep(0.25)

    try:
        Prompt(arguments.projectName)
    except KeyboardInterrupt:
        exit()

elif __name__ == "Wicky":
    print("Using the Wicky project generator!")