
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T13:38:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7468dac687f008da67ccc4394c55e921ce3053b0",
 "version": "2705"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
