
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T10:02:46-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "1532e63f4d99dc761d28f3bc5d999b99c7915d53",
 "version": "v1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
