# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'src'}

packages = \
['lowcode_cli',
 'lowcode_cli.3rd_praty',
 'lowcode_cli.3rd_praty.casbin_adapter',
 'lowcode_cli.3rd_praty.casbin_adapter.migrations',
 'lowcode_cli.3rd_praty.djangoueditor',
 'lowcode_cli.common',
 'lowcode_cli.common.constant',
 'lowcode_cli.common.http',
 'lowcode_cli.common.jinja2',
 'lowcode_cli.common.jsonschema',
 'lowcode_cli.common.log',
 'lowcode_cli.conf',
 'lowcode_cli.core',
 'lowcode_cli.core.auth',
 'lowcode_cli.core.commands',
 'lowcode_cli.core.decorators',
 'lowcode_cli.core.permission',
 'lowcode_cli.core.validators',
 'lowcode_cli.services',
 'lowcode_cli.utils',
 'lowcode_cli.utils.auth',
 'lowcode_cli.utils.oss']

package_data = \
{'': ['*'],
 'lowcode_cli': ['schema/defs/*',
                 'templates/app/*',
                 'templates/blocks/*',
                 'templates/vue-pure-admin/*'],
 'lowcode_cli.3rd_praty.djangoueditor': ['static/ueditor/*',
                                         'static/ueditor/_examples/*',
                                         'static/ueditor/_examples/server/*',
                                         'static/ueditor/dialogs/*',
                                         'static/ueditor/dialogs/anchor/*',
                                         'static/ueditor/dialogs/attachment/*',
                                         'static/ueditor/dialogs/attachment/fileTypeImages/*',
                                         'static/ueditor/dialogs/attachment/images/*',
                                         'static/ueditor/dialogs/background/*',
                                         'static/ueditor/dialogs/background/images/*',
                                         'static/ueditor/dialogs/charts/*',
                                         'static/ueditor/dialogs/charts/images/*',
                                         'static/ueditor/dialogs/emotion/*',
                                         'static/ueditor/dialogs/emotion/images/*',
                                         'static/ueditor/dialogs/gmap/*',
                                         'static/ueditor/dialogs/help/*',
                                         'static/ueditor/dialogs/image/*',
                                         'static/ueditor/dialogs/image/images/*',
                                         'static/ueditor/dialogs/insertframe/*',
                                         'static/ueditor/dialogs/link/*',
                                         'static/ueditor/dialogs/map/*',
                                         'static/ueditor/dialogs/music/*',
                                         'static/ueditor/dialogs/preview/*',
                                         'static/ueditor/dialogs/scrawl/*',
                                         'static/ueditor/dialogs/scrawl/images/*',
                                         'static/ueditor/dialogs/searchreplace/*',
                                         'static/ueditor/dialogs/snapscreen/*',
                                         'static/ueditor/dialogs/spechars/*',
                                         'static/ueditor/dialogs/table/*',
                                         'static/ueditor/dialogs/template/*',
                                         'static/ueditor/dialogs/template/images/*',
                                         'static/ueditor/dialogs/video/*',
                                         'static/ueditor/dialogs/video/images/*',
                                         'static/ueditor/dialogs/webapp/*',
                                         'static/ueditor/dialogs/wordimage/*',
                                         'static/ueditor/lang/en/*',
                                         'static/ueditor/lang/en/images/*',
                                         'static/ueditor/lang/zh-cn/*',
                                         'static/ueditor/lang/zh-cn/images/*',
                                         'static/ueditor/php/*',
                                         'static/ueditor/themes/*',
                                         'static/ueditor/themes/default/*',
                                         'static/ueditor/themes/default/css/*',
                                         'static/ueditor/themes/default/images/*',
                                         'static/ueditor/third-party/*',
                                         'static/ueditor/third-party/SyntaxHighlighter/*',
                                         'static/ueditor/third-party/codemirror/*',
                                         'static/ueditor/third-party/highcharts/*',
                                         'static/ueditor/third-party/highcharts/adapters/*',
                                         'static/ueditor/third-party/highcharts/modules/*',
                                         'static/ueditor/third-party/highcharts/themes/*',
                                         'static/ueditor/third-party/snapscreen/*',
                                         'static/ueditor/third-party/video-js/*',
                                         'static/ueditor/third-party/video-js/font/*',
                                         'static/ueditor/third-party/webuploader/*',
                                         'static/ueditor/third-party/zeroclipboard/*',
                                         'templates/*']}

install_requires = \
['Django>=4.0.6,<5.0.0',
 'Jinja2>=3.1.2,<4.0.0',
 'click>=8.1.3,<9.0.0',
 'convert-case>=1.1.1,<2.0.0',
 'jsonschema>=4.6.1,<5.0.0',
 'pytest>=7.1.2,<8.0.0']

entry_points = \
{'console_scripts': ['lowcode = lowcode_cli.manage:makemigrations']}

setup_kwargs = {
    'name': 'lowcode-cli',
    'version': '0.0.1',
    'description': 'Generate front-end code automatically',
    'long_description': None,
    'author': 'whc',
    'author_email': '249768447@qq.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/status-521/lowcode-cli.git',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.9,<4.0',
}


setup(**setup_kwargs)
