
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-19T16:39:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "23e301d7b71a8b47e5a6c20e31df336bddb4edb5",
 "version": "v0.0.1-alpha2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
