
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-19T15:58:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "77f7e1ca72be1d002108956f1fdfc6c14bd1316e",
 "version": "2711"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
