
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T14:01:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "10a885b94e9c54f904ca6b4f676a21b5ea165c8d",
 "version": "1.2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
