
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T04:04:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "157856d42c2ab821ea99eff58bee8ca23b18f47c",
 "version": "1.17.0.post.dev37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
