VERSION_YEAR = 2022
VERSION_MONTH = int('07')
VERSION_DAY = int('20')
VERSION_HOUR = int('03')
VERSION_MINUTE = int('09')
MAJOR_VERSION = 1
MINOR_VERSION = 5
PATCH_VERSION = 202207200309
version_date = '2022/07/20 03:09'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
