
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-19T06:32:31+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "75bfd9bebf415fabed9ef4ec39d4a0c6ebd94335",
 "version": "0.5.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
