
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-17T23:11:28+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac49db183ee66136be9ff22a16d782c0277c021c",
 "version": "0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
