VERSION_YEAR = 2022
VERSION_MONTH = int('07')
VERSION_DAY = int('19')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('26')
MAJOR_VERSION = 1
MINOR_VERSION = 5
PATCH_VERSION = 202207191826
version_date = '2022/07/19 18:26'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
