
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-18T13:28:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "275c26f13bd28c635e37c1ded064d4ba50b88410",
 "version": "1.16.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
