"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kdp_api
from kdp_api.api.group_memberships_api import GroupMembershipsApi  # noqa: E501


class TestGroupMembershipsApi(unittest.TestCase):
    """GroupMembershipsApi unit test stubs"""

    def setUp(self):
        self.api = GroupMembershipsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_group_memberships_get(self):
        """Test case for group_memberships_get

        """
        pass

    def test_group_memberships_id_delete(self):
        """Test case for group_memberships_id_delete

        """
        pass

    def test_group_memberships_id_get(self):
        """Test case for group_memberships_id_get

        """
        pass

    def test_group_memberships_id_patch(self):
        """Test case for group_memberships_id_patch

        """
        pass

    def test_group_memberships_id_put(self):
        """Test case for group_memberships_id_put

        """
        pass

    def test_group_memberships_post(self):
        """Test case for group_memberships_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
