"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.usage import Usage
globals()['Usage'] = Usage
from kdp_api.model.usage_list import UsageList


class TestUsageList(unittest.TestCase):
    """UsageList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsageList(self):
        """Test UsageList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UsageList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
