"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kdp_api
from kdp_api.api.attributes_api import AttributesApi  # noqa: E501


class TestAttributesApi(unittest.TestCase):
    """AttributesApi unit test stubs"""

    def setUp(self):
        self.api = AttributesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attributes_get(self):
        """Test case for attributes_get

        """
        pass

    def test_attributes_id_delete(self):
        """Test case for attributes_id_delete

        """
        pass

    def test_attributes_id_get(self):
        """Test case for attributes_id_get

        """
        pass

    def test_attributes_id_patch(self):
        """Test case for attributes_id_patch

        """
        pass

    def test_attributes_id_put(self):
        """Test case for attributes_id_put

        """
        pass

    def test_attributes_post(self):
        """Test case for attributes_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
