"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kdp_api
from kdp_api.api.attribute_assignments_api import AttributeAssignmentsApi  # noqa: E501


class TestAttributeAssignmentsApi(unittest.TestCase):
    """AttributeAssignmentsApi unit test stubs"""

    def setUp(self):
        self.api = AttributeAssignmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attribute_assignments_get(self):
        """Test case for attribute_assignments_get

        """
        pass

    def test_attribute_assignments_id_delete(self):
        """Test case for attribute_assignments_id_delete

        """
        pass

    def test_attribute_assignments_id_get(self):
        """Test case for attribute_assignments_id_get

        """
        pass

    def test_attribute_assignments_id_patch(self):
        """Test case for attribute_assignments_id_patch

        """
        pass

    def test_attribute_assignments_id_put(self):
        """Test case for attribute_assignments_id_put

        """
        pass

    def test_attribute_assignments_post(self):
        """Test case for attribute_assignments_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
