"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kdp_api
from kdp_api.api.workspaces_api import WorkspacesApi  # noqa: E501


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self):
        self.api = WorkspacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_workspaces_get(self):
        """Test case for workspaces_get

        """
        pass

    def test_workspaces_id_delete(self):
        """Test case for workspaces_id_delete

        """
        pass

    def test_workspaces_id_get(self):
        """Test case for workspaces_id_get

        """
        pass

    def test_workspaces_id_patch(self):
        """Test case for workspaces_id_patch

        """
        pass

    def test_workspaces_id_put(self):
        """Test case for workspaces_id_put

        """
        pass

    def test_workspaces_post(self):
        """Test case for workspaces_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
