"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.workspaces_subscription import WorkspacesSubscription
globals()['WorkspacesSubscription'] = WorkspacesSubscription
from kdp_api.model.workspace1 import Workspace1


class TestWorkspace1(unittest.TestCase):
    """Workspace1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspace1(self):
        """Test Workspace1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Workspace1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
