"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.group1 import Group1


class TestGroup1(unittest.TestCase):
    """Group1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroup1(self):
        """Test Group1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Group1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
