"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.reported_usage_list import ReportedUsageList
globals()['ReportedUsageList'] = ReportedUsageList
from kdp_api.model.reported_usage_paginator import ReportedUsagePaginator


class TestReportedUsagePaginator(unittest.TestCase):
    """ReportedUsagePaginator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportedUsagePaginator(self):
        """Test ReportedUsagePaginator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReportedUsagePaginator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
