"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kdp_api
from kdp_api.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_get(self):
        """Test case for users_get

        """
        pass

    def test_users_id_delete(self):
        """Test case for users_id_delete

        """
        pass

    def test_users_id_get(self):
        """Test case for users_id_get

        """
        pass

    def test_users_id_patch(self):
        """Test case for users_id_patch

        """
        pass

    def test_users_id_put(self):
        """Test case for users_id_put

        """
        pass

    def test_users_post(self):
        """Test case for users_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
