from enum import Enum

class Province(Enum):
  aceh = "Aceh"
  bali = "Bali"
  bangka_belitung = "BangkaBelitung"
  banten = "Banten"
  bengkulu = "Bengkulu"
  dki_yogyakarta = "DIYogyakarta"
  dki_jakarta = "DKIJakarta"
  gorontalo = "Gorontalo"
  jambi = "Jambi"
  jawa_barat = "JawaBarat"
  jawa_tengah = "JawaTengah"
  jawa_timur = "JawaTimur"
  kalimantan_barat = "KalimantanBarat"
  kalimantan_selatan = "KalimantanSelatan"
  kalimantan_tengah = "KalimantanTengah"
  kalimantan_timur = "KalimantanTimur"
  kalimantan_utara = "KalimantanUtara"
  kepulauan_riau = "KepulauanRiau"
  lampung = "Lampung"
  maluku = "Maluku"
  maluku_utara = "MalukuUtara"
  nusa_tenggara_barat = "NusaTenggaraBarat"
  nusa_tenggara_timur = "NusaTenggaraTimur"
  papua = "Papua"
  papua_barat = "PapuaBarat"
  riau = "Riau"
  sulawesi_barat = "SulawesiBarat"
  sulawesi_selatan = "SulawesiSelatan"
  sulawesi_sengah = "SulawesiTengah"
  sulawesi_tenggara = "SulawesiTenggara"
  sulawesi_utara = "SulawesiUtara"
  sumatera_barat = "SumateraBarat"
  sumatera_selatan = "SumateraSelatan"
  sumatera_utara = "SumateraUtara"
  indonesia = "Indonesia"