
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-13T19:08:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "061e5249b61854c8bbbb8ebbe06d93fed9b52df5",
 "version": "0.23b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
