
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T10:44:40-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca7897b01221d9d575466a7b79fa57ff6ec6dcc4",
 "version": "1.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
