
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T15:09:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c3ffbfe29a602669cd7864f0a6632f1231d2333",
 "version": "1.9.1b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
