
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-13T16:35:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4dc8753174282a35bc8c67d4d865b96d35dd7d4",
 "version": "0.45.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
