
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-13T04:23:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7e2b7120fedaaec01de3a75bb460995192efc5a",
 "version": "0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
