
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T10:42:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "eeecc030a0870907da7a5356ece9469a90933b75",
 "version": "1.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
